### ISSUE TITLE
Schedule supplementary meeting times

### ISSUE THREAD

**Issue by alice** [w3ctag/meetings#35]
For predictable work sessions which do not require a full quorum.

**Comment by alice** [comment]
@dbaron commented in slack:

> Here's one option for paired calls; these could potentially be shifted an hour earlier if people would rather do 8am meetings than 5pm/6pm meetings, or similar.  These are times for the July half of the year.
```UTC:          Thu 2019-05-23 08:00 UTC
Sydney:       Thu 2019-05-23 18:00 AEST
Tokyo:        Thu 2019-05-23 17:00 JST
Paris:        Thu 2019-05-23 10:00 CEST
London:       Thu 2019-05-23 09:00 BST
San Francisco:not used

UTC:          Thu 2019-05-23 16:00 UTC
Sydney:       not used
Tokyo:        not used
Paris:        Thu 2019-05-23 18:00 CEST
London:       Thu 2019-05-23 17:00 BST
San Francisco:Thu 2019-05-23 09:00 PDT

UTC:          Fri 2019-05-24 00:00 UTC
Sydney:       Fri 2019-05-24 10:00 AEST
Tokyo:        Fri 2019-05-24 09:00 JST
Paris:        not used
London:       not used
San Francisco:Thu 2019-05-23 17:00 PDT
```

**Comment by dbaron** [comment]
The equivalent for the January half of the year might be:

```
UTC:          Thu 2020-01-23 09:00 UTC
Sydney:       Thu 2020-01-23 20:00 AEDT
Tokyo:        Thu 2020-01-23 18:00 JST
Paris:        Thu 2020-01-23 10:00 CET
London:       Thu 2020-01-23 09:00 GMT
San Francisco:not used

UTC:          Thu 2020-01-23 17:00 UTC
Sydney:       not used
Tokyo:        not used
Paris:        Thu 2020-01-23 18:00 CET
London:       Thu 2020-01-23 17:00 GMT
San Francisco:Thu 2020-01-23 09:00 PST

UTC:          Fri 2020-01-24 00:00 UTC
Sydney:       Fri 2020-01-24 11:00 AEDT
Tokyo:        Fri 2020-01-24 09:00 JST
Paris:        not used
London:       not used
San Francisco:Thu 2020-01-23 16:00 PST
```

I'd also note some people may want to shift a few hours later so that their time is after dinnertime.  We need to solicit preferences on that point...

**Comment by dbaron** [comment]
To be clear:  the use case here is that we'd like to try doing more work in two or three person breakouts between face-to-face meetings.  Having some reserved times for that would make it more likely for that to work, and for any given two people on the TAG at least one of the above breakouts would be possible.  If we schedule three person breakouts we'd need to constrain the choice of three people to include at most two of (a) North America (b) Europe and (c) East Asia / Australia.

**Comment by dbaron** [comment]
our discussion had many digressions, but I think it's probably preferable to move the one that's 9am California one hour earlier, although @hober didn't like it.

We can also use ad-hoc time slots rather than these time slots when two people are in the same/similar timezones.

**Comment by hober** [comment]
Closing, since we've been on the new, 3-breakouts-and-plenary schedule for a while now.
