### ISSUE TITLE
Discussion of Pronunciation Task Force Work

### ISSUE THREAD

**Issue by alia11y** [w3ctag/meetings#38]
こんにちはTAG!

I'm requesting TAG presence at the following meeting during TPAC:

  - Group: APA's Pronunciation Task Force
  - Topic: Various technical approaches to support required features of Spoken Text Pronunciation, Presentation and existing standards
  - Specification URL:  https://www.w3.org/WAI/APA/task-forces/pronunciation/
  - Explainer (containing user needs and example code)¹: https://github.com/w3c/pronunciation
  - GitHub issues (if you prefer feedback filed there): [url]
  - Preferred date and timeframe: September 20, Friday, 11AM

When the meeting agenda and specific room has been finalized, we request the groups to note these details as comments in this issue.

Please note that we will not officially register as observers, as the assignee for presence will not be decided until all the groups have sent in requests.

**Comment by torgo** [comment]
Hi @alia11y. If it's ok with you we would prefer to tackle this and the other request you made in the same session. We suggest that we do this at Thursday at 11 as @alice is already scheduled to join you then.

**Comment by alia11y** [comment]
It should work on Thursday at 11. Mark @mhakkinen , can you make it on Thursday?

**Comment by cynthia** [comment]
Visited and discussed. Summary is that we acknowledge this is trying to solve a valid use case, and we have left an actionable item for @mhakkinen to file a review for us to look into.

(Repo: https://github.com/w3ctag/design-reviews/issues )
