### ISSUE TITLE
WebAuthn Discussions

### ISSUE THREAD

**Issue by nadalin** [w3ctag/meetings#39]
こんにちはTAG!

I'm requesting TAG presence at the following meeting during TPAC:

  - Group: WebAuthn
  - Topic: General Discussion, direction on Level 2
  - Specification URL: https://www.w3.org/TR/webauthn/ 
  - Explainer (containing user needs and example code)¹: https://www.w3.org/TR/webauthn/ 
  - GitHub issues (if you prefer feedback filed there): [url]
  - Preferred date and timeframe: Friday Afternoon

When the meeting agenda and specific room has been finalized, we request the groups to note these details as comments in this issue.

Please note that we will not officially register as observers, as the assignee for presence will not be decided until all the groups have sent in requests.

**Comment by torgo** [comment]
@cynthia will be there on Friday early afternoon.

**Comment by cynthia** [comment]
We did visit the meeting room, but it was unclear what we were expected from us. The timeslot we walked in happened to be bug bashing of current open issues in the WG.

Not sure if the v2/next directions ever even made it to the agenda, based on this information:
https://lists.w3.org/Archives/Public/public-webauthn/2019Sep/0072.html
