### ISSUE TITLE
Immersive Web Working Group TPAC Meeting Request

### ISSUE THREAD

**Issue by AdaRoseCannon** [w3ctag/meetings#40]
こんにちはTAG!

I'm requesting TAG presence at the following meeting during TPAC:

  - Group: Immersive Web Working Group
  - Topic: WebXR Device API
  - Specification URL: https://immersive-web.github.io/webxr/
  - Explainer: https://github.com/immersive-web/webxr/blob/master/explainer.md
  - GitHub issues: https://github.com/immersive-web/webxr/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
  - Preferred date and timeframe: Monday Afternoon Please

When the meeting agenda and specific room has been finalized, we request the groups to note these details as comments in this issue.

Please note that we will not officially register as observers, as the assignee for presence will not be decided until all the groups have sent in requests.

Tagging @cwilso the other co-chair of the Working Group

**Comment by torgo** [comment]
We're confirming we will definitely be there. Have discussed with @cwilso us joining after lunch on Monday.

**Comment by cynthia** [comment]
We had some actions that we should probably log here before we close this.

**Comment by hober** [comment]
@cynthia wrote:

> We had some actions that we should probably log here before we close this.

Did those actions get logged?
