### ISSUE TITLE
Accessibility, Declarative Semantics and WebAssembly, WebGPU, WebGL

### ISSUE THREAD

**Issue by joshueoconnor** [w3ctag/meetings#41]
In terms of support for explicit declarative semantics, what are the relative advantages of WebAssembly (WASM), WebGPU, or WebGL (including glTF) to support accessibility as well as generic applications? Which of these provide the best architecture?  This is being asked in the context of current communication by platform and browser accessibility APIs as well as implications for any future incarnations.

For example, in the Accessible Platform Architectures Working Group (APA) we note the current performance improvements in WASM, via the WebIDL Bindings proposal for better memory management and direct WASM => browser calls. This reference binding expressions from linear memory looks more efficient and potentially better/faster for accessibility related API calls, as well as generic API calls where semantics can be consumed by Assistive Technology.

Some semantics can be inferred in 3D environments and games, for example WebGL-glTF has potential due its ability to generate classes via JSON schema. These rendering environments may also support semantic scene graphs, which can describe the relationships between objects for example.

It would be great if the TAG could share their understanding of the three technologies from a semantic layering perspective. We look forward to discussing this and hearing your thoughts. We will also be having a breakout session at TPAC on XR Accessibility and TAG members are very welcome to attend that, as well as our APA meetings.

Thanks

Josh (Emerging Web Tech W3C/WAI)

**Comment by dbaron** [comment]
Is this a request to have some TAG members specifically [this breakout](https://www.w3.org/wiki/TPAC/2019/SessionIdeas#XR_Accessibility)?

Is there a particular time at the APA meeting that you wanted to have a discussion?

**Comment by joshueoconnor** [comment]
Hi @dbaron It would be great if there could be a TAG presence at the [APA Friday session 11-12 AM](https://www.w3.org/WAI/APA/wiki/Meetings/TPAC_2019), would this be doable?

**Comment by torgo** [comment]
As discussed in #38, members of the TAG will join on Thursday at 11.

**Comment by joshueoconnor** [comment]
Ok, great - wfm.
