### ISSUE TITLE
Web & Networks Interest Group TAG TPAC Meeting Request

### ISSUE THREAD

**Issue by sudeepdi** [w3ctag/meetings#42]
こんにちはTAG!

I'm requesting TAG presence at the following meeting during TPAC:

  - Group: Web & Networks IG
  - Topic: Usage of hints (network or application) to improve Web QoE
  - Specification URL: [spec url]
  - Explainer (containing user needs and example code)¹: https://www.w3.org/2019/05/web-networks-ig-charter.html
  - GitHub issues (if you prefer feedback filed there): https://github.com/w3c/web-networks/issues
  - Preferred date and timeframe: Tuesday 17th 

When the meeting agenda and specific room has been finalized, we request the groups to note these details as comments in this issue.

Please note that we will not officially register as observers, as the assignee for presence will not be decided until all the groups have sent in requests.

Tagging co-chairs @gsimcard, Dan and Dom @dontcallmedom  to

**Comment by cynthia** [comment]
@ylafon will confirm the time.

**Comment by sudeepdi** [comment]
We would like to close this request as we reviewed our readiness for an Architecture presentation, and think we still need more time to prepare to be ready to solicit feedback from TAG during TPAC. Therefore, closing this issue. However, we would like to welcome any one from TAG to join the meeting to get an insight of what we are doing today and share areas where we may need support in the near future.

Copying chairs @gsimcard and Dan, and Dom @dontcallmedom
