### ISSUE TITLE
DID WG/TAG 

### ISSUE THREAD

**Issue by brentzundel** [w3ctag/meetings#47]
こんにちはTAG!

I'm requesting TAG presence at the following virtual meeting during TPAC 2020:

  - Group: DID WG
  - Topic: TAG Review of DID Spec
  - Specification URL: https://www.w3.org/TR/did-core/
  - Explainer (containing user needs and example code)¹: https://github.com/w3c/did-wg/blob/master/did-explainer.md
  - GitHub issues (if you prefer feedback filed there): https://github.com/w3c/did-core/issues
  - Agenda of your meeting: https://tinyurl.com/yydapmu3
  - Preferred date and timeframe: [November 3, 2020 19:30 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?p1=43&iso=20201103T1430&msg=DId%20WG%20and%20TAG&am=30&sort=2)
  - Meeting Link: https://lists.w3.org/Archives/Member/member-did-wg/2020Jun/0000.html

When the meeting agenda and specific room has been finalized, we request the groups to note these details as comments in this issue.

Please note that we will not officially register as observers, as the assignee for presence will not be decided until all the groups have sent in requests.

**Comment by torgo** [comment]
@hober and @hadleybeeman will be there.

**Comment by brentzundel** [comment]
@hober and @hadleybeeman the meeting link is in here: https://lists.w3.org/Archives/Member/member-did-wg/2020Jun/0000.html

**Comment by hober** [comment]
@atanassov
