### ISSUE TITLE
Explore Possible Web Components "Best Practices" Guide?

### ISSUE THREAD

**Issue by torgo** [w3ctag/meetings#9]
As discussed at the April 2015 f2f.

**Comment by travisleithead** [comment]
Thinking out loud here...
- Appropriate accessibility semantics for the component
  - ARIA markup
  - Focus/Tab order management
  - Activation (space bar/enter key) handling (if any)
- Use attributes as a primary control mechanism (making your component easily serializable)
- Sub-divide complex components into multiple components if possible (minimal semantic element behavior principle)
- Customizable Style should use CSS Custom Property names.

**Comment by plinss** [comment]
See https://github.com/webcomponents/gold-standard/wiki
